### ISSUE TITLE
Is there anyway i can contact you in private?

### ISSUE THREAD

**Issue by gwendolynemaxinegwenstacy** [gato-louco/greasemonkey-scripts#1]
Hey I want to ask you some private questions about one of your programs. Is there anyway I can contact you?

Discord or anything? Thank you.

**Comment by gato-louco** [comment]
> Hey I want to ask you some private questions about one of your programs. Is there anyway I can contact you?
> 
> Discord or anything? Thank you.

gatoloucooficial@protonmail.com
